
CREATE DATABASE `jdr` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
use `jdr`;

CREATE USER 'u_jdr'@'localhost' IDENTIFIED BY 'SJzEeqLb2HHeNYVV';
GRANT USAGE ON * . * TO 'u_jdr'@'localhost' IDENTIFIED BY 'SJzEeqLb2HHeNYVV' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;
GRANT ALL PRIVILEGES ON `jdr` . * TO 'u_jdr'@'localhost';

-- Table des utilisateurs
-- DROP TABLE IF EXISTS `T_UTILISATEUR_UTI`;

CREATE TABLE IF NOT EXISTS `T_UTILISATEUR_UTI` (
  `UTI_ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `UTI_LOGIN` varchar(255) NOT NULL,
  `UTI_MAIL` varchar(255) NOT NULL,
  `UTI_NOM` varchar(255) NOT NULL,
  `UTI_PRENOM` varchar(255) NOT NULL,
  `UTI_PASS` varchar(40) NOT NULL,
  `UTI_ADMIN` tinyint(1) NOT NULL DEFAULT '0',
  `UTI_AVATAR` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`UTI_ID`),
  UNIQUE KEY `UTI_LOGIN` (`UTI_LOGIN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

-- Table des unités
-- DROP TABLE IF EXISTS T_UNITE_UNI;
CREATE TABLE  T_UNITE_UNI (
  UNI_LABEL varchar(30) NOT NULL,
  UNI_SHORT_LABEL varchar(15) NOT NULL,
  UNI_DESCRIPTION mediumtext NOT NULL,
  UNI_VALIDE bool NOT NULL DEFAULT 0,
  UTI_ID  bigint(20) unsigned NOT NULL,
  KEY (UTI_ID),
  PRIMARY KEY (UNI_LABEL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;


-- Table des publications
-- DROP TABLE IF EXISTS T_PUBLICATION_PUB;
CREATE TABLE   T_PUBLICATION_PUB (
  PUB_ID  bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  PUB_DATE timestamp NOT NULL DEFAULT NOW(), 
  PUB_TITRE varchar(80) NOT NULL,
  PUB_DESCRIPTION longtext NOT NULL,
  PUB_DUREE time NOT NULL,
  PUB_DIFFICULTE ENUM("facile","moyen","difficile") NOT NULL DEFAULT 'facile',
  PUB_STATUT ENUM("brouillon","soumise","finale") NOT NULL DEFAULT 'brouillon',
  PUB_ILLUSTRATION varchar(80) NOT NULL,    
  UTI_ID bigint(20) unsigned NOT NULL,
  PUB_NBPERSONNE int NOT NULL,
  PRIMARY KEY (PUB_ID),
  KEY (UTI_ID) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;


 
-- Table des catégories
-- DROP TABLE IF EXISTS T_CATEGORIE_CAT;
CREATE TABLE  T_CATEGORIE_CAT (
  CAT_ID bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  CAT_LABEL varchar(255) NOT NULL,
  CAT_DESCRIPTION mediumtext NOT NULL,
  CAT_ILLUSTRATION varchar(80) NOT NULL,  
  PRIMARY KEY (CAT_ID)  
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;


-- Table d'association entre publications et  catégories
-- DROP TABLE IF EXISTS TJ_CAT_PUB;
CREATE TABLE  TJ_CAT_PUB (
  CAT_ID bigint(20) unsigned NOT NULL,
  PUB_ID bigint(20) unsigned NOT NULL,  
  PRIMARY KEY (CAT_ID, PUB_ID),
  KEY (CAT_ID),
  KEY (PUB_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

-- Table des ingrédients
-- DROP TABLE IF EXISTS T_INGREDIENT_IGD;
CREATE TABLE  T_INGREDIENT_IGD (
  IGD_LABEL varchar(255) NOT NULL,
  IGD_DESCRIPTION mediumtext NOT NULL,
  IGD_ILLUSTRATION varchar(80) NULL DEFAULT NULL,
  IGD_VALIDE bool NOT NULL DEFAULT 0,
  UTI_ID bigint(20) unsigned NULL DEFAULT NULL,
  PRIMARY KEY (IGD_LABEL),
  KEY (IGD_LABEL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;



-- Table d'association (composer)des publications, ingédients et unités
-- DROP TABLE IF EXISTS TJ_IGD_PUB_UNI;
CREATE TABLE  TJ_IGD_PUB_UNI (
  PUB_ID bigint(20) unsigned NOT NULL,
  IGD_LABEL varchar(255)  NOT NULL,
  UNI_LABEL varchar(30) NOT NULL,
  IGD_PUB_UNI_QUANTITE int(11) NOT NULL,      
  PRIMARY KEY (PUB_ID, IGD_LABEL, UNI_LABEL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;


 
-- Table de commentaires
-- DROP TABLE IF EXISTS T_COMMENTAIRE_COM;
CREATE TABLE  T_COMMENTAIRE_COM (
  COM_ID bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  COM_TEXTE mediumtext NOT NULL,
  COM_DATE timestamp NOT NULL DEFAULT NOW(), 
  UTI_ID bigint(20) unsigned NULL,
  PUB_ID bigint(20) unsigned NOT NULL,
  PRIMARY KEY (COM_ID),
  KEY (PUB_ID),
  KEY (UTI_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

    
-- création des clés étrangéres
                                
ALTER TABLE TJ_CAT_PUB
 ADD CONSTRAINT C_FK_CAT_CAT_PUB FOREIGN KEY (CAT_ID) REFERENCES T_CATEGORIE_CAT (CAT_ID) ,
 ADD CONSTRAINT C_FK_PUB_CAT_PUB FOREIGN KEY (PUB_ID) REFERENCES T_PUBLICATION_PUB (PUB_ID) ;
 
ALTER TABLE  T_UNITE_UNI        
     ADD CONSTRAINT C_FK_UNI_UTI FOREIGN KEY (UTI_ID) REFERENCES T_UTILISATEUR_UTI (UTI_ID) ;
    
ALTER TABLE T_COMMENTAIRE_COM
 ADD CONSTRAINT C_FK_UTI_COM FOREIGN KEY (UTI_ID) REFERENCES T_UTILISATEUR_UTI (UTI_ID) ,
 ADD CONSTRAINT C_FK_PUB_COM FOREIGN KEY (PUB_ID) REFERENCES T_PUBLICATION_PUB (PUB_ID) ;

ALTER TABLE TJ_IGD_PUB_UNI
 ADD CONSTRAINT C_FK_PUB_IGD_PUB_UNI FOREIGN KEY (PUB_ID) REFERENCES T_PUBLICATION_PUB (PUB_ID) ,
 ADD CONSTRAINT C_FK_IGD_IGD_PUB_UNI FOREIGN KEY (IGD_LABEL) REFERENCES T_INGREDIENT_IGD(IGD_LABEL), 
 ADD CONSTRAINT C_FK_UNI_IGD_PUB_UNI FOREIGN KEY (UNI_LABEL) REFERENCES T_UNITE_UNI (UNI_LABEL) ;

ALTER TABLE T_INGREDIENT_IGD
 ADD CONSTRAINT C_FK_UTI_IGD FOREIGN KEY (UTI_ID) REFERENCES T_UTILISATEUR_UTI (UTI_ID) ;

ALTER TABLE T_PUBLICATION_PUB
 ADD CONSTRAINT C_FK_UTI_PUB FOREIGN KEY (UTI_ID) REFERENCES T_UTILISATEUR_UTI (UTI_ID) ;
  